name: Build and Deploy Tweego

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Tweego
        run: |
          curl -L -o tweego.zip https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
          unzip tweego.zip -d tweego-bin
          chmod +x tweego-bin/tweego
          echo "$PWD/tweego-bin" >> $GITHUB_PATH

      - name: Build Twine Project
        run: |
          tweego -o out/index.html src/index.twee  # Adjust this to your actual folder structure

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Wherever output.html ended up
          # publish_branch: gh-pages
          # force_orphan: true  # Optional: keeps gh-pages clean
          #just a comment to force a rebuild 